function doGet(e) {
  var sheet = SpreadsheetApp.getActiveSpreadsheet().getActiveSheet();
  var data = sheet.getRange(1, 1).getValue() || "{}";
  var callback = e && e.parameter ? e.parameter.callback : "";

  // JSONP is required because the dashboard is hosted on GitHub Pages.
  // Only allow a JavaScript identifier generated by the dashboard.
  if (callback && /^[A-Za-z_$][0-9A-Za-z_$]*$/.test(callback)) {
    return ContentService.createTextOutput(callback + "(" + data + ");")
      .setMimeType(ContentService.MimeType.JAVASCRIPT);
  }

  return ContentService.createTextOutput(data)
    .setMimeType(ContentService.MimeType.JSON);
}

function doPost(e) {
  var lock = LockService.getScriptLock();
  lock.waitLock(10000);
  try {
    var sheet = SpreadsheetApp.getActiveSpreadsheet().getActiveSheet();
    var json = e && e.postData ? e.postData.contents : "";

    // Validate before replacing the current cloud copy.
    var parsed = JSON.parse(json);
    if (!parsed.version || !Array.isArray(parsed.sessions) || !Array.isArray(parsed.courses)) {
      throw new Error("Invalid dashboard data");
    }

    sheet.getRange(1, 1).setValue(json);
    SpreadsheetApp.flush();
    return ContentService.createTextOutput(JSON.stringify({ status: "success" }))
      .setMimeType(ContentService.MimeType.JSON);
  } finally {
    lock.releaseLock();
  }
}
